# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestTui < Formula
  desc "Terminal UI for browsing and running IntelliJ HTTP Client .http scratch files"
  homepage "https://github.com/Ahngbeom/rest-tui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ahngbeom/rest-tui/releases/download/v0.1.0/rest-tui_0.1.0_darwin_amd64.tar.gz"
      sha256 "3b6bd16382848b13b307720f4c059237ad06df33c33bcc60c44fa28629f61c29"

      define_method(:install) do
        bin.install "rest-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ahngbeom/rest-tui/releases/download/v0.1.0/rest-tui_0.1.0_darwin_arm64.tar.gz"
      sha256 "a9cbec0e328434e18a195bc337a95eb6edc31d71ce33188667d5c2629d10044d"

      define_method(:install) do
        bin.install "rest-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ahngbeom/rest-tui/releases/download/v0.1.0/rest-tui_0.1.0_linux_amd64.tar.gz"
      sha256 "f5c3dc8850146beeb5b9a862e424d832b1508dd154c610416b17bed54f0b7452"
      define_method(:install) do
        bin.install "rest-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ahngbeom/rest-tui/releases/download/v0.1.0/rest-tui_0.1.0_linux_arm64.tar.gz"
      sha256 "97045a411ec4e6d68a8b35e2dd18a3cbabaef161e9df9489c5403c9dff3cc248"
      define_method(:install) do
        bin.install "rest-tui"
      end
    end
  end
end
