# This file was generated by GoReleaser. DO NOT EDIT.
cask "dv" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "bcf48cc39a2b058a425631107d5d84744214f24a3c809195f644c25f1957fe0b"
      url "https://github.com/Ahngbeom/datavase/releases/download/v#{version}/dv_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dc8c24fa55e9c4c4c1a6011014441abc52823ceafa4d3f2a0952eca4a24421bb"
      url "https://github.com/Ahngbeom/datavase/releases/download/v#{version}/dv_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "75648c5e2031ef8b281b70009660305cee7387928aa1d325e6574a915969e45c"
      url "https://github.com/Ahngbeom/datavase/releases/download/v#{version}/dv_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "668ee102704fcf055ca27a08dbd068ac7c84704ef0acdd9950c6aff16aaa54d6"
      url "https://github.com/Ahngbeom/datavase/releases/download/v#{version}/dv_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "dv"
  desc "A terminal MySQL/MariaDB client. Single static binary, no runtime, no IDE."
  homepage "https://github.com/Ahngbeom/datavase"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dv"]
    end
  end

  # No zap stanza required
end
