# This file was generated by GoReleaser. DO NOT EDIT.
cask "dv" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "971f62ff62c065bd52e3009245cc1782a1de8c0c133a5a2af1d691b785f75769"
      url "https://github.com/Ahngbeom/datavase/releases/download/v#{version}/dv_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2e955560b4f5755db0ff8394814f0c77b51b1a74e157a239e226fec11fdfaf16"
      url "https://github.com/Ahngbeom/datavase/releases/download/v#{version}/dv_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ad65dbb6b7b780130b2ecf6cdd715c92765053e9b65d5473e1cb85974076ec6e"
      url "https://github.com/Ahngbeom/datavase/releases/download/v#{version}/dv_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1d0817f33787a4e29b86217cf49bc701da92e9d588f2d0b0f2e06c51492cb860"
      url "https://github.com/Ahngbeom/datavase/releases/download/v#{version}/dv_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "dv"
  desc "A terminal MySQL/MariaDB client. Single static binary, no runtime, no IDE."
  homepage "https://github.com/Ahngbeom/datavase"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dv"]
    end
  end

  # No zap stanza required
end
