# This file was generated by GoReleaser. DO NOT EDIT.
cask "dv" do
  version "0.11.1"

  on_macos do
    on_arm do
      sha256 "e0c8ef79fdefe78f3690856b019ebd6922db88119680abbb9e9cf2e679c0bada"
      url "https://github.com/Ahngbeom/datavase/releases/download/v#{version}/dv_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6851ee126cfbef23e617e20c4bcc1aed05d54ef7ae6fc945c695694fb78a3b2d"
      url "https://github.com/Ahngbeom/datavase/releases/download/v#{version}/dv_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2561b728d2fb1b36aa33250db6e3f0be4d8b7b70b25f4fa9e7ae4f5422c9839e"
      url "https://github.com/Ahngbeom/datavase/releases/download/v#{version}/dv_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "23723a4141010368a706265c08266c66970e3040856962b44b76637b75b9ba71"
      url "https://github.com/Ahngbeom/datavase/releases/download/v#{version}/dv_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "dv"
  desc "A terminal MySQL/MariaDB client. Single static binary, no runtime, no IDE."
  homepage "https://github.com/Ahngbeom/datavase"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dv"]
    end
  end

  # No zap stanza required
end
