# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestTui < Formula
  desc "Terminal UI for browsing and running IntelliJ HTTP Client .http scratch files"
  homepage "https://github.com/Ahngbeom/rest-tui"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ahngbeom/rest-tui/releases/download/v0.2.1/rest-tui_0.2.1_darwin_amd64.tar.gz"
      sha256 "de42aea2153a0c8d823c10bf5f1d9d83e76fc4b5238a230eb9ccb64992d37d56"

      define_method(:install) do
        bin.install "rest-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ahngbeom/rest-tui/releases/download/v0.2.1/rest-tui_0.2.1_darwin_arm64.tar.gz"
      sha256 "f847b81303e24d58c51d5769a5b1fd057199e8e023e2151346d42382622fb1f1"

      define_method(:install) do
        bin.install "rest-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ahngbeom/rest-tui/releases/download/v0.2.1/rest-tui_0.2.1_linux_amd64.tar.gz"
      sha256 "f29c0930e83c2d84b2045e645ce72ce4c254bf7d1315390773896e95191e6365"
      define_method(:install) do
        bin.install "rest-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ahngbeom/rest-tui/releases/download/v0.2.1/rest-tui_0.2.1_linux_arm64.tar.gz"
      sha256 "f9ed66d7612df9656900d02f7b9e17a0e82b427a5d2295e23bf7024a5cbc4d87"
      define_method(:install) do
        bin.install "rest-tui"
      end
    end
  end
end
