# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestTui < Formula
  desc "Terminal UI for browsing and running IntelliJ HTTP Client .http scratch files"
  homepage "https://github.com/Ahngbeom/rest-tui"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ahngbeom/rest-tui/releases/download/v0.2.2/rest-tui_0.2.2_darwin_amd64.tar.gz"
      sha256 "3c489b654b35f11f7cd827673386e54c7890163d697512ff1fd6a99c7c844f68"

      define_method(:install) do
        bin.install "rest-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ahngbeom/rest-tui/releases/download/v0.2.2/rest-tui_0.2.2_darwin_arm64.tar.gz"
      sha256 "2540f8ca9fd9bfa91b18b236694cbbe1350161f238da9a2faaa966f79d1402bb"

      define_method(:install) do
        bin.install "rest-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ahngbeom/rest-tui/releases/download/v0.2.2/rest-tui_0.2.2_linux_amd64.tar.gz"
      sha256 "9ebf1b9afd7c99c5e52ef5711161e4deb9abdd865eff2f0a23875dd98cc8ccae"
      define_method(:install) do
        bin.install "rest-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ahngbeom/rest-tui/releases/download/v0.2.2/rest-tui_0.2.2_linux_arm64.tar.gz"
      sha256 "abbb40680d37e6296d7e5108efa561e24915ac4644a1d2f1fd9343a094ef5c0e"
      define_method(:install) do
        bin.install "rest-tui"
      end
    end
  end
end
